global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'adoption-app'
    metrics_path: '/adoption/actuator/prometheus'
    static_configs:
      - targets: ['adoption-app:8089']
    scrape_interval: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']